project:
  type: website
  render:
    - "*.qmd"
    - "!blog/"

website:
  title: "blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  repo-url: https://github.com/zheng-alice/blog
  repo-actions: [source]

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
